#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_MIN_MOTOR_TEMPERATURE_C          20
#define APP_WARNING_MOTOR_TEMPERATURE_C      80
#define APP_SHUTDOWN_MOTOR_TEMPERATURE_C    100
#define APP_MIN_PWM_DUTY_PERCENT             10
#define APP_MAX_PWM_DUTY_PERCENT             90
#define APP_TEMPERATURE_FILTER_SAMPLE_COUNT   8
#define APP_TARGET_MOTOR_SPEED_RPM         3000
#define APP_MAX_ALLOWED_SPEED_ERROR_RPM     500

#endif
